services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: go-fiber-skeleton-dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GOFLAGS=-buildvcs=false
    volumes:
      - .:/app
      - /go/pkg/mod
      - /app/tmp